services:
    api.controller.forum:
        class: phpbb_controller_api_forum
        arguments:
            - @model.repository.forum
            - @config
            - @model.repository.auth
            - @request

    api.controller.topic:
        class: phpbb_controller_api_topic
        arguments:
            - @model.repository.topic
            - @config

    api.controller.auth:
        class: phpbb_controller_api_auth
        arguments:
            - @model.repository.auth
            - @user
            - @controller.helper
            - @template
            - @request
            - @config
