services:
    api.controller.forum:
        class: phpbb\controller\api\forum
        arguments:
            - @model.repository.forum
            - @config
            - @model.repository.auth

    api.controller.auth:
        class: phpbb\controller\api\auth
        arguments:
            - @model.repository.auth
            - @user
            - @controller.helper
            - @template
            - @request
            - @config
            - @auth

    api.controller.topic:
            class: phpbb\controller\api\topic
            arguments:
                - @model.repository.topic
                - @model.repository.post
                - @model.repository.auth
                - @config

    api.controller.post:
            class: phpbb\controller\api\post
            arguments:
                - @model.repository.post
                - @model.repository.auth
                - @request
                - @config
                - %core.root_path%
                - %core.php_ext%

    api.controller.version:
            class: phpbb\controller\api\version
            arguments:
                - @config
