# Structure:
#
# foo_controller:
#     pattern: /foo
#     defaults: { _controller: foo_sevice:method }
#
# The above will be accessed via app.php?controller=foo and it will
# instantiate the "foo_service" service and call the "method" method.
#
api_forums_controller:
    pattern: /api/forums/{forum_id}
    defaults: { _controller: api.controller.forum:forums, forum_id: 0 }
    requirements:
        forum_id: \d+
        _method: GET

api_topics_controller:
    pattern: /api/forums/{forum_id}/topics/{page}
    defaults: { _controller: api.controller.topic:topics, page: 1 }
    requirements:
        forum_id: \d+
        page: \d+
        _method: GET

api_auth_generate_controller:
    pattern: /api/auth/generatetoken
    defaults: { _controller: api.controller.auth:generate_token }
    requirements:
        _method: GET

api_auth_controller:
    pattern: /api/auth/{token}/{sign_token}
    defaults: { _controller: api.controller.auth:auth }
    requirements:
        _method: GET

api_auth_allow_controller:
    pattern: /api/auth/allow
    defaults: { _controller: api.controller.auth:allow }
    requirements:
        _method: POST

api_auth_verify_controller:
    pattern: /api/auth/verify/{token}/{timestamp}/{hash}
    defaults: { _controller: api.controller.auth:verify }
    requirements:
        _method: GET

